/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
 allprojects {
     repositories {

         jcenter()



     }
 }

 subprojects {
     version = "2.0.0-SNAPSHOT"
     apply(plugin = "java")
 }

plugins {
  "kotlin"
}

project(":tests") {
    dependencies {
        "implementation"(project(":lambdas:s3objectcreated"))
    }

}




 
